### ISSUE TITLE
Error when the server is not found!

### ISSUE THREAD

**Issue by henrythierrydevalt** [Henry8K/Minescord#1]
> I've been testing the entire bot and it's perfect, in everything, I just found this error!

```
[5:13 PM] TypeError: Cannot read properties of undefined (reading 'online')
[5:13 PM]     at Object.execute (/application/commands/about/status.js:70:46)
[5:13 PM]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[5:13 PM]     at async Client.<anonymous> (/application/Index.js:57:5)
[5:13 PM] [Minescord] => [C] Critical => An unknown error occurred in the Status command!
[5:13 PM] [Minescord] => [L] Log => Send the log to: https://github.com/Henry8K/Minescord
```

**Comment by henrythierrydev** [comment]
Fixed! Download de bot: 

https://github.com/Henry8K/Minescord/

**Comment by henrythierrydevalt** [comment]
Thanks
